name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
#   build-and-test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Install Java
#         uses: actions/setup-java@v2
#         with:
#           java-version: '11'
#           distribution: 'adopt'

#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Package & verify
#         run:  mvn verify
#         env:
#           ACTIVE_PROFILE: "dev"
#           DEV_DBNAME: ${{secrets.DEV_DBNAME}}
#           DEV_USERNAME: ${{secrets.DEV_USERNAME}}
#           DEV_PASSWORD: ${{secrets.DEV_PASSWORD}}
  docker:
    runs-on: ubuntu-latest
#     needs: build-and-test
    env:
      ACTIVE_PROFILE: "dev"
      DEV_DBNAME: ${{secrets.DEV_DBNAME }}
      DEV_USERNAME: ${{secrets.DEV_USERNAME}}
      DEV_PASSWORD: ${{secrets.DEV_PASSWORD}}
      
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ github.event.repository.name }}:latest, ${{ github.repository }}:latest
